services:
  influxdb:
    image: influxdb:1.11.8
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=logger_db
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_READ_USER=grafana
      - INFLUXDB_READ_USER_PASSWORD=password
      - INFLUXDB_WRITE_USER=logger
      - INFLUXDB_WRITE_USER_PASSWORD=password
    volumes:
      - ./influxdb_data:/var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=nate
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - influxdb
    volumes:
      - ./grafana_data:/var/lib/grafana
